### ISSUE TITLE
Configuration guide

### ISSUE THREAD

**Issue by nhandl3** [MartinBrugnara/CaptivePortal#3]
Hi Martin,
This project is pretty cool :)
Could you please give an instruction to config this captive portal with an access point?

**Comment by MartinBrugnara** [comment]
Hi @whyka ,
Thank you =)

If you mean install it directly on an AP... i never tried...
In fact I have only tried it on VMs.
I hope I will have more time to work on this side project in the future weeks...

Anyway I would try to answer:
I suppose that setting  ```IN_DEV="wlan0"``` in scripts/init_captive.sh should be enough to do the trick.

P.S. do not create a bridge between ```wlan0``` and ```eth0```. All the traffic has to be processed by iptables.

**Comment by MartinBrugnara** [comment]
Instead if you mean how to configure it to work with an AP..
You have to set ```IN_DEV=<port which AP is connected to>```. 
Bonus if you have more then one... just put a switch and install it only on the machine that act as Gateway..

```
AP0 --,
AP1 ---  SWITCH ---   (GW with Captive) -- other net (or Internet)
AP2 --'
```

**Comment by whyka** [comment]
Thank you for your response,
Your answer connect AP in LAN is what I want.
I will try this configuration and contribute more for README if possible :)

**Comment by MartinBrugnara** [comment]
@whyka You are welcome
